// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextWatch.Core.Data;

#nullable disable

namespace NextWatch.Core.Data.Migrations
{
    [DbContext(typeof(NextWatchDbContext))]
    partial class NextWatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("NextWatch.Core.Domain.Entities.AlertEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CheckId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepeatCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FiredAtUtc");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("NextWatch.Core.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CheckId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepeatMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToastEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WebhookEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CheckId");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("NextWatch.Core.Domain.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlertsMutedUntilRestart")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AlertsMutedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultWebhookUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanSharedSecretHash")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LanViewerEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanViewerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSeenReleaseVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MonitoringPaused")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortableDataDirectory")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PortableDataPath")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StartWithWindows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlertsMutedUntilRestart = false,
                            LanViewerEnabled = false,
                            LanViewerPort = 5080,
                            MonitoringPaused = false,
                            OnboardingCompleted = false,
                            PortableDataPath = false,
                            RetentionDays = 30,
                            StartWithWindows = false,
                            Theme = "Dark"
                        });
                });

            modelBuilder.Entity("NextWatch.Core.Domain.Entities.CheckDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveSuccesses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRunUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarnThreshold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NextRunUtc");

                    b.HasIndex("TargetId");

                    b.ToTable("Checks");
                });

            modelBuilder.Entity("NextWatch.Core.Domain.Entities.CheckResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CheckId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LatencyMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("CheckId", "TimestampUtc");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("NextWatch.Core.Domain.Entities.MonitorTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MuteUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Tag");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("NextWatch.Core.Domain.Entities.AlertRule", b =>
                {
                    b.HasOne("NextWatch.Core.Domain.Entities.CheckDefinition", "Check")
                        .WithMany("AlertRules")
                        .HasForeignKey("CheckId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Check");
                });

            modelBuilder.Entity("NextWatch.Core.Domain.Entities.CheckDefinition", b =>
                {
                    b.HasOne("NextWatch.Core.Domain.Entities.MonitorTarget", "Target")
                        .WithMany("Checks")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("NextWatch.Core.Domain.Entities.CheckResult", b =>
                {
                    b.HasOne("NextWatch.Core.Domain.Entities.CheckDefinition", "Check")
                        .WithMany("Results")
                        .HasForeignKey("CheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Check");
                });

            modelBuilder.Entity("NextWatch.Core.Domain.Entities.CheckDefinition", b =>
                {
                    b.Navigation("AlertRules");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("NextWatch.Core.Domain.Entities.MonitorTarget", b =>
                {
                    b.Navigation("Checks");
                });
#pragma warning restore 612, 618
        }
    }
}
